/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/*int mybspatch(int argc,char * argv[]);*/

/* Header for class com_xhiston_arouterdemo_DiffUpdateUtil */

#ifndef _Included_com_xhiston_arouterdemo_DiffUpdateUtil
#define _Included_com_xhiston_arouterdemo_DiffUpdateUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xhiston_arouterdemo_DiffUpdateUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */

JNIEXPORT jint JNICALL Java_com_xhiston_arouterdemo_DiffUpdateUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
